spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zorth?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: Yannian002.

server:
  port: 9527